# Generated by Django 4.2 on 2023-04-21 00:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ministry', models.CharField(max_length=500)),
                ('contractor', models.CharField(max_length=500)),
                ('local_gov', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('contract_sum', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'in progress'), ('DONE', 'done')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=500)),
                ('projects', models.CharField(max_length=500)),
                ('head', models.CharField(max_length=500)),
                ('members', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=500)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd_app.project')),
                # ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='pd_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=20)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd_app.project')),
                # ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pd_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'in progress'), ('DONE', 'done')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], max_length=20)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd_app.project')),
                # ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pd_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('uploaded_by', models.CharField(max_length=500)),
                ('uploaded_at', models.DateField()),
                ('file_url', models.CharField(max_length=1000)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd_app.project')),
                # ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_doc', to='pd_app.project')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd_app.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pd_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                # ('milestone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tag', models.CharField(choices=[('ON_SCHEDULE', 'on schedule'), ('BEHIND_SCHEDULE', 'behind schedule')], max_length=20)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd_app.project')),
                # ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='pd_app.project')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd_app.task')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=2500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pd_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Issue_Action',
            fields=[
                ('issue_action_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('committed_by', models.CharField(max_length=500)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd_app.project')),
                # ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issueaction', to='pd_app.project')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd_app.task')),
            ],
        ),
    ]
