# Generated by Django 4.2 on 2023-04-21 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pd_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pd_app.project'),
            preserve_default=False,
        ),
    ]
